# Generated by Django 4.2 on 2023-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
