# Generated by Django 4.2 on 2023-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_productdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_db',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='categoryprofile'),
        ),
    ]
