# Generated by Django 4.2 on 2023-05-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_db_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_db',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
